[build.environment]
  HUGO_VERSION = "0.154.4"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.25.5"
  NODE_VERSION = "24.12.0"
  TZ = "Europe/London" 

[build]
  publish = "public"
  command = "hugo --gc --minify --baseURL $URL"